# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # <--- BU SATIR ÅžART
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      TZ: 'Europe/Istanbul'
      FTLCONF_webserver_api_password: ${API_PASSWORD}
      FTLCONF_dns_listeningMode: 'ALL'

      FTLCONF_webserver_port: 80

      LOCAL_DOMAIN: ${LOCAL_DOMAIN}
      TARGET_IP: ${TARGET_IP}

      DNS1: cloudflared#5053

      FTLCONF_misc_etc_dnsmasq_d: 'true'
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - ./etc-pihole:/etc/pihole

      # baslangic scripti
      - ./scripts/custom-start.sh:/custom-start.sh
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      # - ./etc-dnsmasq.d:/etc/dnsmasq.d
    entrypoint: 
      ["/custom-start.sh"]
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    networks:
      - proxy-agim
      - dns-internal
    depends_on:
      - cloudflared

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command: proxy-dns --address 0.0.0.0 --port 5053 --upstream https://1.1.1.1/dns-query --upstream https://1.0.0.1/dns-query
    restart: always
    networks:
      - dns-internal

networks:
  proxy-agim:
    external: true
    name: nginx-main
  dns-internal:
    driver: bridge
