services:
  nginx:
    image: nginx
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "80:80"
    volumes:
        - ./default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - LOCAL_DOMAIN=${LOCAL_DOMAIN}
    networks:
      - proxy-agim

networks:
  proxy-agim:
    external: true
    name: nginx-main
